### ISSUE TITLE
Layer loaded but prettier-before-save doesn't work

### ISSUE THREAD

**Issue by zhiwei-nu** [praveenperera/spacemacs-prettier#1]
Hey, I followed your README and successfully loaded the prettier layer ( i think) but the `prettier-before-save` function doesn't work. Any idea why?

**Comment by praveenperera** [comment]
Which mode are you in when you tried it? It should work in `js-mode` or `react-mode`

**Comment by zhiwei-nu** [comment]
@praveenperera thanks for pointing that out! I added 
```
(require 'prettier-js)
(setq prettier-target-mode "js2-mode")
``` 
and it works :+1:

**Comment by praveenperera** [comment]
Awesome, I'll add that as a default
