### ISSUE TITLE
Disable prettier before save hook

### ISSUE THREAD

**Issue by Nolski** [praveenperera/spacemacs-prettier#2]
It'd be nice if we had some docs on how to disable the before save hook for users who only wanted to explicitly call prettier. I currently have no idea how to do that.

**Comment by praveenperera** [comment]
I am thinking of solving this and #3 by removing all the before-save hooks which are currently enabled by default. And adding instructions in the readme showing how to enabled them individually in the `.spacemacs` file. Thoughts @Nolski @jessejanderson?

**Comment by Nolski** [comment]
This sounds good to me. Thanks!

**Comment by ezmiller** [comment]
I tried to follow your guide in the README for configuring the run on save hooks but they don't seem to be working. I added them like so:

```
(defun dotspacemacs/user-config ()
  "Configuration function for user code.
This function is called at the very end of Spacemacs initialization after
layers configuration.
This is the place where most of your configurations should be done. Unless it is
explicitly specified that a variable should be set before a package is loaded,
you should place your code here."
  (mac-auto-operator-composition-mode t)
  (setq js-indent-level 2)
  (add-hook 'js2-mode-hook 'prettier-js-mode)
  (add-hook 'web-mode-hook 'prettier-js-mode)
  )
```

Any idea why the on-save behavior might not be working even with these hooks added?
