### ISSUE TITLE
Disable Prettier for JSON

### ISSUE THREAD

**Issue by jessejanderson** [praveenperera/spacemacs-prettier#3]
I'm getting prettier errors whenever I save a .json file (I'm assuming because of some sort of `.js*` catchall. Any way to easily disable that?

**Comment by praveenperera** [comment]
I removed all the default on save hooks (#4) you can now add only the ones you want in your `.spacemacs` file. I have the following ones in mine and its working with json fine.

```elisp
  (add-hook 'js2-mode-hook 'prettier-js-mode)
  (add-hook 'web-mode-hook 'prettier-js-mode)
  (add-hook 'react-mode-hook 'prettier-js-mode)

```
