### ISSUE TITLE
install on spacemacs

### ISSUE THREAD

**Issue by LouisDelbosc** [praveenperera/spacemacs-prettier#7]
It seems prettier is now on MELPA (cf https://github.com/melpa/melpa/pull/4777) and the repo description is `Adds prettier-js formatter to spacemacs locally. Temporary solution until prettier-js is launched on MELPA`.

How can I install the prettier-layer using the spacemacs package manager ? 

Also, thank you for your work ! :)

**Comment by praveenperera** [comment]
So looks like it has been added as a package but I don't think spacemacs has added it to any of the layers. 

To install the package just add `prettier-js` to `dotspacemacs-additional-packages` in your spacemacs file.

PS: If you installed prettier using this layer make sure you remove it. No need to have to versions of the same thing floating around.
